-- Retained migration identifier for compatibility with existing databases.
-- Admin accounts are created through Supabase Auth with individual credentials.
-- An owner grants a role through a private administrative database session.
-- No accounts, identities or passwords are provisioned from public source.
